
export let mockData = [
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 119,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 141,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'lllskks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 211,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 311,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 119,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 141,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'lllskks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 211,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 311,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 119,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 141,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'lllskks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 211,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 311,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 119,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 141,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'lllskks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 211,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 311,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 701,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sallaa',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 783,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ewwi29',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 101,
    Name: 'Max',
    RegNo: 124334255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'xxvcb',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 102,
    Name: 'Max',
    RegNo: 122332255,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'ksjdd',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 103,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 104,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 121,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: 'sjsjlks',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
  {
    Id: 612,
    Name: 'Max',
    RegNo: 122334455,
    Sire: 'Dassy Pax',
    Dam: 'Rex Pax',
    Sex: 'Male',
    Dob: '20240112',
    PreTitle: 'CHF',
    PostTitle: 'GS',
    Cotation: '',
    Color: 'Black',
    Height: 10,
    Weight: 40,
    Breeder: 'Frank Bard',
    Owner: 'Gemini Dave',
    Country: 'South Africa',
    Breeding: 'Not Active',
    IdentificationNo: '1234567890',
  },
]
